spring:
  datasource:
    url : "jdbc:mysql://127.0.0.1:3306/redis"
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  jmx:
    enabled: false
  data:
    redis:
      host: 127.0.0.1
      port: 6379