server:
  port: 9000
  tomcat:
    max-connections: 10000
    accept-count: 1000
    threads:
      min-spare: 1000
      max: 3000

logging:
  level:
    root: info


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fastsns
    username: root
    password: fastcampus
  data:
    redis:
      host: localhost
      port: 6379